# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

[character]
success_symbol = '[➜](bold green)'
error_symbol = '[✗](bold red)'

[cmd_duration]
min_time = 10_000  # show command duration over 10,000 milliseconds (=10 sec)
format = "\n(took [$duration]($style))"

[package]
disabled = true

[git_branch]
symbol = ""
# truncation_length = 20
# truncation_symbol = ''
# ignore_branches = ['master', 'main']
