tap "jdblackstar/tap"
tap "microsoft/mssql-release", "https://github.com/Microsoft/homebrew-mssql-release"
brew "bats-core"
brew "cask"
brew "d2"
brew "eza"
brew "fzf"
brew "gh"
brew "go"
brew "neovim"
brew "node"
brew "python@3.12"
brew "ripgrep"
brew "smartmontools"
brew "starship"
brew "tmux"
brew "unixodbc"
brew "uv"
brew "zoxide"
brew "jdblackstar/tap/relay", trusted: true
brew "microsoft/mssql-release/msodbcsql17"
cask "ghostty"
