PROFILE_NAME="agent"
PROFILE_GITCONFIG="$DOTFILES_DIR/git/agent.gitconfig"
PROFILE_MACOS_BREWFILES=()
PROFILE_LINUX_PACKAGE_FILES=()
PROFILE_INSTALL_OH_MY_ZSH=0
PROFILE_INSTALL_TPM=1
PROFILE_RUN_MACOS_DEFAULTS=0
PROFILE_LINK_RELAY=1
